# Generated by Django 4.2.10 on 2025-05-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag_app_apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apidocument',
            name='local_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
